services:
  broker:
    image: shajen/broker:${BROKER_TAG:-latest}
    env_file: .env
    restart: on-failure
    ports:
      - ${MQTT_PORT_TCP:-1883}:${MQTT_PORT_TCP:-1883}
      - ${MQTT_PORT_WS:-9001}:${MQTT_PORT_WS:-9001}
  sdr-scanner:
    image: shajen/sdr-scanner:${SDR_SCANNER_TAG:-latest}
    env_file: .env
    restart: on-failure
    depends_on:
      - broker
    volumes:
      - sdr_config:/config
    devices:
      - /dev/bus/usb:/dev/bus/usb
  monitor-setup:
    image: shajen/monitor:${MONITOR_TAG:-latest}
    env_file: .env
    restart: on-failure
    depends_on:
      - broker
    volumes:
      - monitor_db:/usr/src/sdr-panel/db
      - monitor_data:/usr/src/sdr-panel/public/media
    command: /entrypoint/setup.sh
  monitor-server:
    image: shajen/monitor:${MONITOR_TAG:-latest}
    env_file: .env
    restart: on-failure
    depends_on:
      monitor-setup:
        condition: service_completed_successfully
    volumes:
      - monitor_db:/usr/src/sdr-panel/db
      - monitor_data:/usr/src/sdr-panel/public/media
    command: /entrypoint/server.sh
    ports:
      - ${HTTP_PORT:-8000}:8000
  monitor-worker:
    image: shajen/monitor:${MONITOR_TAG:-latest}
    env_file: .env
    restart: on-failure
    depends_on:
      monitor-setup:
        condition: service_completed_successfully
    volumes:
      - monitor_db:/usr/src/sdr-panel/db
      - monitor_data:/usr/src/sdr-panel/public/media
    command: /entrypoint/worker.sh
volumes:
  sdr_config:
  monitor_db:
  monitor_data:
